### ISSUE TITLE
Function Advice

### ISSUE THREAD

**Issue by xxhk-org** [dive2Pro/roam-toolbar#2]
Thank you for your roam-toolbar in Roam Depot.
  
Could you add a bar to add references like [[keywords]], because the character of "[[]]" can not be typed directly in the Chinese environment.

We will appreciate your extra work very much.

Best wishes. :)

**Comment by dive2Pro** [comment]
@LeoChanXY of course, i will add it in the next version.

**Comment by dive2Pro** [comment]
it's on depot now.

**Comment by xxhk-org** [comment]
> it's on depot now.

非常感谢！
