### ISSUE TITLE
Roam Studio incompatibility

### ISSUE THREAD

**Issue by melikarslan** [dive2Pro/roam-toolbar#4]
I've already [reported this issue to Roam Studio](https://github.com/rcvd/RoamStudio/issues/31), but I am posting here too, because I'm not sure if you or Roam Studio developer can fix it.

Roam Toolbar extension works normally when Roam Studio is disabled, but it looks weird if Roam Studio is enabled AND there is a text under the highlighted passage.

I've added screenshots to illustrate the problem. Hope you can fix it so we use this small but great extension without issues.

Thanks

<img width="688" alt="224994515-fe2baa83-5b22-4582-8d8a-594a72b674f3" src="https://user-images.githubusercontent.com/36539736/224996895-8fb9dae8-54c0-4e40-89cc-5ee28ccf80ec.png">
<img width="670" alt="224994523-d3269a4f-6701-4664-b116-8bd1230ed9b9" src="https://user-images.githubusercontent.com/36539736/224996920-77facc4d-b16b-4e60-8c34-8ed42805442f.png">
<img width="693" alt="224994602-1efa19c5-788a-48ef-928c-d4e0b7a854aa" src="https://user-images.githubusercontent.com/36539736/224996937-14ed1dc1-bfda-4894-af69-d36bfede4dfd.png">

**Comment by dive2Pro** [comment]
hey, This is because Roam Studio has changed the background color of the button element. You can fix it using the following code:

```css
.rm-toolbar button.bp3-button {
    background-color: red(change color here);
}
```

**Comment by melikarslan** [comment]
thanks a lot
